### ISSUE TITLE
有没有打算更好的支持 swift？

### ISSUE THREAD

**Issue by NeverAgain11** [Lision/LSAnimator#10]
rt

**Comment by Lision** [comment]
现在这种方式确实对swift调用不是很友好，群里有小伙伴建议我抽出来一个类做 Animator 而不是使用分类，又或者使用 swift 的扩展？由于自己公司的项目还没有使用 swift，一直被耽搁下来了。

嘛~ 感谢提出宝贵建议，我会选一种方式对 swift 友好支持的。更多问题欢迎进去讨论哈！

**Comment by JunyiXie** [comment]
我过两天用Swift的方式包装一下就可以了

**Comment by Lision** [comment]
@NeverAgain11 你好，如你所见，在 2017 年的最后一天我终于把这个库的 v2.x 实现了，已经完美支持 Swift（主流 3.2 - 4），感谢你的关注和建议。
