### ISSUE TITLE
为什么我用cocoapods导入LSAnimator会不完整？

### ISSUE THREAD

**Issue by devYoungyang** [Lision/LSAnimator#15]
为什么我用cocoapods导入LSAnimator会不完整？
目录
<img width="232" alt="2018-01-27 13 40 41" src="https://user-images.githubusercontent.com/17973681/35469055-b307cfbc-0367-11e8-8e70-9cc4e8311cd7.png">

**Comment by Lision** [comment]
Hi～ 看目录结构你的应该是老版本的 LSAnimator
请更新一下CocoaPods 的 repo 再试试？

Young <notifications@github.com>于2018年1月27日 周六13:41写道：

**Comment by devYoungyang** [comment]
1.4.0cocoapods

**Comment by Lision** [comment]
Emmmmm... 可能是我没说清楚，不是指 CocoaPods 的版本哟
尝试 `$ pod search LSAnimator` 之后看看搜索到的 LSAnimator 是否是最新版本（截止目前是 2.1.2）
如果不是，尝试执行下面的命令：

``` shell
$ pod sutup
$ rm ~/Library/Caches/CocoaPods/search_index.json
```
