### ISSUE TITLE
demo真机运行就崩溃

### ISSUE THREAD

**Issue by hms040717007** [Lision/LSAnimator#16]

**Comment by Lision** [comment]
这个问题貌似是 Xcode 的一个 Bug ... 
https://stackoverflow.com/questions/41549131/dyld-abort-with-payload-error-on-iphone-5s-device
实际集成到自己的项目没有问题的。

**Comment by Lision** [comment]
@hms040717007 你好：
如果查到其他的解决办法也欢迎留言一起交流哟~

**Comment by Lision** [comment]
Hi~ @hms040717007 
I have found a way to solve the problem.
[this is the link](https://stackoverflow.com/questions/24333981/ios-app-with-framework-crashed-on-device-dyld-library-not-loaded-xcode-6-beta)
