### ISSUE TITLE
为何LSAnimator的platform变成9.0了？ autoreverses属性支持吗？

### ISSUE THREAD

**Issue by woaiaizi001** [Lision/LSAnimator#17]
😖

**Comment by Lision** [comment]
由于之前在 UIColor  的转换上使用了一个 API [CGColorCreateCopyByMatchingToColorSpace](https://developer.apple.com/documentation/coregraphics/1455493-cgcolorcreatecopybymatchingtocol) 这个 API 是 iOS 9 之后加入标准库的。

另外 暂不支持 autoreverses -_-|| 不过我会考虑一下哈
