### ISSUE TITLE
使用过程中，不知道由于什么原因会导致动画过程闪烁

### ISSUE THREAD

**Issue by iWECon** [Lision/LSAnimator#22]
出现闪烁后会影响到所有使用 LSAnimator 动画的效果😳

**Comment by Lision** [comment]
请问是在什么样的情况下出现这类问题的呢？
- 模拟器 or 真机（具体机型）
- 如果可以的话，新建一个 Demo 工程将动画代码移入其中，Run 一下看是否还会闪烁
如果还有问题的话，可以加我的微信 lixin_oo，尝试定位问题。

**Comment by wanghao522** [comment]
iphone xr 12.2 ，确实会影响到所有动画，执行动画的时候会先再动画执行后的位置出现一下再消失，然后从默认位置开始执行动画

**Comment by wanghao522** [comment]
[view drawViewHierarchyInRect:screenRect afterScreenUpdates:YES]; 程序中执行过此代码后会影响到所有LSAnimator的动画

**Comment by wanghao522** [comment]
库没有问题 主要是drawViewHierarchyInRect:screenRect afterScreenUpdates:Yes 这个截屏操作调用过后会影响所有GPU上的动画，可以将afterScreenUpdates参数设置为NO，或者使用另外的截屏方法：view.layer renderInContext:UIGraphicsGetCurrentContext()

**Comment by Lision** [comment]
@wanghao522 
强势，如果已解决的话我就先 Close 了

**Comment by iWECon** [comment]
> 库没有问题 主要是drawViewHierarchyInRect:screenRect afterScreenUpdates:Yes 这个截屏操作调用过后会影响所有GPU上的动画，可以将afterScreenUpdates参数设置为NO，或者使用另外的截屏方法：view.layer renderInContext:UIGraphicsGetCurrentContext()

三克油
