### ISSUE TITLE
关于JHChainableAnimator 的组合动画

### ISSUE THREAD

**Issue by Eflet** [Lision/LSAnimator#6]
看了下你的Blog，你执行了2遍animate，所以是后面冲掉前面的animation了
这种情况你只要执行第2个animate， 第一个animate去掉，就是个组合动画。
JHChainableAnimator *animator = [[JHChainableAnimator alloc] initWithView:_animatorView];
animator.makeCornerRadius(20).thenAfter(2).moveY(100)；
animator.makeOpacity(0).animate(4);
JHChainableAnimator 是能做组合动画的，你举的例子代码写的不对。

不过对CALayer的支持挺不错，最近正好要用到，赞一个。

**Comment by Eflet** [comment]
好吧又看了下你写的例子，看上去你是故意这么写的，就是为了说明多链式动画的问题。
你例子里的问题，是不是把变透明分成2段，0-2秒变淡50%，2-4秒再完全透明，就能用JHChainableAnimator 解决了。

这个库在写复杂动画的时候应该有用，不过暂时还没想到有啥场景要用多个group的动画来处理~

**Comment by Lision** [comment]
@Eflet “0-2秒变淡50%，2-4秒再完全透明” 这只是强改，多数情况下的复杂交互这么改也不能达到UE设计的动画效果，且如果设计变更也会需要在自己脑中重新分割类似文中的透明变化动画（还不见得能跟着形变链恰好分割完）。文章中主要是想说明一些复杂交互场景会使用 JHChainableAnimator 会非常乏力，这个库是我在使用 JHChainableAnimator 做交互时自己不止一次遇到过类似于文中的场景后所做，类似透明度与背景色等跟形变位置无关的复杂动画交互都有可能让 JHChainableAnimator 变得乏力

**Comment by Eflet** [comment]
另外大佬，还是希望和原版一样不用category的方式。我也网上查了下侵入式框架的概念，我觉得2边都不是侵入式的框架，并没有要求一定要继承某个View才能用这个动画框架。原版的几个版本之前也是用的Category的方式，最近才改成这种非Hacking的样子，这样耦合度更低更好用的。
我现在的项目就是，只用暴露这个animator出去而不用整个View都暴露出去处理动画。

**Comment by Lision** [comment]
@Eflet 感谢你的反馈，我会收集一下这方面的意见之后选择修改的哈~

**Comment by Lision** [comment]
@Eflet 正在改成非 Hacking 模式，v2.0.0 将会改变模式并且会全面支持 Swift 3.2~4.0。

**Comment by Lision** [comment]
@Eflet 如你所见，在 2017 年末我把这个库更新到了 v2.x，去掉了之前骇客的写法，改为使用 Animator 绑定 view。同时加入了 JH 不具备的特性：
- 支持 CALayer
- 支持参数自动补全
- 支持多链式动画
这个 issue 我准备 close 掉了，感谢你最开始的关注和建议。
